; =======================================================
; ARCHIVO DE CONFIGURACIÓN DE PYFR - configuracion.ini
; Casos: Caso 1 base y Caso 1 redondeado
; =======================================================

[backend]
precision = double
rank-allocator = linear
[backend-openmp]
cflags = -O3

[constants]
gamma = 1.4
mu = 5e-3 ; Viscosidad dinamica del aire
Pr = 0.71

[solver]
system = navier-stokes
order = 3
shock-capturing = entropy-filter

[solver-entropy-filter]
d-min = 1e-6
p-min = 1e-6
e-tol = 1e-6
niters = 2

[solver-time-integrator]
scheme = rk4
controller = none
tstart = 0.0
tend = 1000.0
dt = 0.0005

[solver-interfaces]
riemann-solver = hllc
ldg-beta = 0.5
ldg-tau = 0.1

[solver-interfaces-line]
flux-pts = gauss-legendre
quad-deg = 10
quad-pts = gauss-legendre

[solver-elements-quad]
soln-pts = gauss-legendre
quad-deg = 10
quad-pts = gauss-legendre

[solver-elements-tri]
soln-pts = williams-shunn
quad-deg = 10
quad-pts = williams-shunn

[solver-elements-line]
soln-pts = williams-shunn
quad-pts = default

[soln-ics]
rho = 1
u = (2/3)/55
v = 0.0
p = 7.937

[soln-bcs-inlet]
type = char-riem-inv
rho = 1
u = 1-4*y*y
v = 0.0
p = 7.937

[soln-bcs-outlet]
type = char-riem-inv
rho = 1
u = (2/3)/55
v = 0.0
p = 7.937

[soln-bcs-bisel]
type = no-slp-adia-wall

[soln-bcs-wall]
type = no-slp-adia-wall

[soln-plugin-nancheck]
nsteps = 1

[soln-plugin-fluidforce-bisel]
nsteps = 1
; --- Sustituir ’caso_X’ por el caso correspondiente ---
file = caso_X_bisel_forces.csv
header = true
quad-deg = 6
morigin = (4.0, -0.5)

[soln-plugin-sampler]
nsteps = 1
samp-pts = [(0.1, 0.5), (0.1, 0.0), (0.1, -0.5), (2.0, 0.5), (2.0, 0.0), (2.0, -0.5), (3.9, 0.4), (3.9, -0.1), (3.9, -0.6), (3.9, 3.9), (3.9, -4.1)]
format = primitive
; --- Sustituir ’caso_X’ por el caso correspondiente ---
file = caso_X_probes.csv
header = true

[soln-plugin-writer]
dt-out = 1
basedir = .
; --- Sustituir ’caso_X’ por el caso correspondiente ---
basename = caso_X-{t:.2f}